project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "!CONTRIBUTING.md"

execute:
  freeze: true

website:
  title: "extendr"
  site-url: https://extendr.github.io
  repo-url: https://github.com/extendr/extendr.github.io
  repo-branch: main
  repo-actions: [edit, issue]
  favicon: "/images/extendr-gears-logo.png"
  page-navigation: true
  bread-crumbs: true

  navbar:
    search: true
    right:
      - text: "INSTALL"
        href: get-started.qmd
      - text: DOCS
        menu:
          - text: "User Guide"
            href: user-guide/index.qmd
          - text: "{extendr} crates"
            href: https://extendr.github.io/extendr/
          - text: "{rextendr} package"
            href: https://extendr.github.io/rextendr/dev
          - text: "Intro to Rust"
            href: intro-rust/index.qmd
          - text: "Contributing"
            href: contributing/index.qmd
      - text: "NEWS"
        href: blog/index.qmd
      - icon: github
        href: https://github.com/extendr/extendr
      - icon: discord
        href: https://discord.gg/7hmApuc

  sidebar:
    - id: rust-basics
      title: "Rust Basics"
      collapse-level: 2
      contents:
        - section: "Rust Basics"
          href: intro-rust/index.qmd
          contents:
            - intro-rust/hello-world.qmd
            - intro-rust/types.qmd
            - intro-rust/control-flow.qmd
            - intro-rust/collections.qmd
            - intro-rust/loops.qmd
            - intro-rust/mutability.qmd
            - intro-rust/functions.qmd
            - intro-rust/ownership.qmd
            - intro-rust/iterators.qmd
            - intro-rust/structures.qmd
            - intro-rust/implementations.qmd
            - intro-rust/enumerations.qmd

    - id: guide
      title: "User Guide"
      collapse-level: 3
      contents:
        - section: "User Guide"
          href: user-guide/index.qmd
          contents:
            - user-guide/complete-example.qmd
            - section: "Core Concepts"
              contents:
                - user-guide/data-types.qmd
                - user-guide/extendr-macro.qmd
            - section: "Type Mapping"
              contents:
                - user-guide/scalars.qmd
                - user-guide/vectors.qmd
                - user-guide/collections.qmd
                - user-guide/into-list.qmd
                - user-guide/default-args.qmd
            - section: "R Packages"
              contents:
                - user-guide/package-structure.qmd
            - section: "Integrations"
              contents:
                - user-guide/serde-integration.qmd
                - user-guide/tokio.qmd
                - user-guide/webr.qmd
            - section: "Publishing"
              contents:
                - user-guide/cran-publishing.qmd
                - user-guide/cran-msrv.qmd
            - user-guide/faq.qmd

    - id: contributing
      title: "Contributing"
      collapse-level: 2
      contents:
        - section: "Contributing"
          href: contributing/index.qmd
          contents:
            - contributing/writing-code.qmd
            - contributing/documenting-code.qmd
            - contributing/testing-code.qmd
            - contributing/extendr-internals.qmd
            - contributing/rextendr-internals.qmd
            - contributing/colors-and-fonts.qmd

format:
  html:
    html-table-processing: none
    theme:
      light: [flatly, css/extendr.scss]
      dark: [darkly, css/extendr.scss]
    toc: true
    toc-location: right
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

# this currently does not work
# see: https://github.com/quarto-dev/quarto-cli/issues/3157
engine: knitr

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
