set default-list

# Compile Tailwind css, then build the site with Zola
build: tailwind-build
    zola build

# Generate Tailwind static/style.css from css/style.css
tailwind-build:
    bunx @tailwindcss/cli -i css/style.css -o static/style.css --minify

# Try to build site without rendering (checks links)
check:
    zola check

# Run Tailwind watch and Zola live serve in parallel
[parallel]
dev: tailwind-watch zola-serve

[private]
tailwind-watch:
    bunx @tailwindcss/cli -i css/style.css -o static/style.css --watch

[private]
zola-serve:
    zola serve --open

# Clear public directory generated by Zola
reset:
    rm -rf public

# Install Node.js dependencies
install: bun basecoat
    @echo "Successfully installed dependencies and copied basecoat files to static."

[private]
bun:
    bun install

[private]
basecoat:
    mkdir -p static/js/
    cp node_modules/basecoat-css/dist/js/*.min.js static/js/

# Create a new documentation page at r-markdown/{{path}}.qmd
page path:
    Rscript r-markdown/_scripts/page.R {{ path }}

# Create a new blog post at r-markdown/blog/{{title}}/index.qmd
post title:
    Rscript r-markdown/_scripts/post.R {{ title }}

# Render page or project in r-markdown/ (ignores r-markdown/blog/ when rendering project)
render path=".":
    Rscript r-markdown/_scripts/knitr.R {{ path }}
